input:
  folder: null
  file_pattern: "*.obj"

output:
  folder: null
  overwrite: true
  temp_img_dir: temp_image
  output_video: temp_video

# scene:

camera:
  track_axis: 'TRACK_NEGATIVE_Z'
  up_axis: 'UP_Y'
  Distance_ratio: 3
  R_xy_angle: 90
  R_z_angle: 45

light:
  type: AREA
  position_bias: [0, 2, 2]
  kwargs:
    energy: 250
    size: 5
    color: [1, 1, 1]

render:
  set_note: true
  resolution_x: 1280
  resolution_y: 720
  resolution_percentage: 100
  engine: BLENDER_EEVEE_NEXT # Use 'BLENDER_EEVEE' for older versions
  kwargs:
    taa_render_samples: 8

video:
  fps: 30
